version: '3'

services:

  server:
    image: nginx:alpine
    restart: always
    depends_on:
      - web
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
      - ./media:/app/media

  web:
    image: dmitriishilkin/antipoff:latest
    command: bash -c "/app/run.sh"
    restart: always
    env_file:
      - .env
    volumes:
      - ./static:/app/static
      - ./media:/app/media
      - app-db:/app/db

volumes:
  app-db:
